# Generated by Django 5.1.7 on 2025-03-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="city",
        ),
        migrations.RemoveField(
            model_name="report",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="report",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="report",
            name="name",
        ),
        migrations.RemoveField(
            model_name="report",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="report",
            name="user",
        ),
    ]
